project/urls.py
from django.contrib import admin
from django.urls import path,include
from testweb import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('testweb.urls')),
]


testweb/urls.py
from django.contrib import admin
from django.urls import path,include
from testweb.views import TestSet
from rest_framework import routers
from testweb import views

app_name = 'testweb'


router = routers.DefaultRouter()
router.register(r'tests',TestSet)


urlpatterns = [
    path('/',include(router.urls)),
    path('signup',views.signup,name='Signup'),
    path('',views.front,name='Front'),
    path('signin',views.signin,name='Signin'),
    path('signinteacher',views.signinteacher,name='Signinteacher'),
    path('forget',views.forget,name='Forget'),
    path('home',views.home,name='Home'),
    path('hometeacher',views.hometeacher,name='Hometeacher'),
    path('signup',views.signup,name='Signupstudent'),
    path('signupteacher',views.signupteacher,name='Signupteacher'),
    path('logout',views.logout,name='logout'),
    path('logoutteacher',views.logoutteacher,name='logoutteacher'),
    path('tests',views.tests,name='tests'),
    path('paperset',views.paperset,name='paperset'),
    path('totalquestion',views.totalquestion,name='totalquestion'),
    path('marks',views.marks,name='marks'),
    path('calculate',views.calculate,name='calculate'),
    path('calculatep',views.calculatep,name='calculatep'),
    path('calculatec',views.calculatec,name='calculatec'),
    path('calculatem',views.calculatem,name='calculatem'),
    path('result',views.result,name='result'),
    path('resultp',views.resultp,name='resultp'),
    path('resultc',views.resultc,name='resultc'),
    path('resultm',views.resultm,name='resultm'),
    path('results',views.results,name='results'),
    path('resultsp',views.resultsp,name='resultsp'),
    path('resultsc',views.resultsc,name='resultsc'),
    path('resultsm',views.resultsm,name='resultsm'),
    path('changepassword/<token>/',views.changepassword,name='Changepassword'),
    path('confirm',views.confirm,name='confirm'),
    path('notconfirm',views.notconfirm,name='notconfirm'),
    path('physics',views.physics,name='physics'),
    path('chemistry',views.chemistry,name='chemistry'),
    path('gs',views.gs,name='gs'),
    path('mathtest',views.mathtest,name='mathtest'),
    path('physicstest',views.physicstest,name='physicstest'),
    path('chemistrytest',views.chemistrytest,name='chemistrytest'),
    path('math',views.math,name='math'),
    path('linkexpired',views.linkexpired,name='linkexpired'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

testweb/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.hashers import make_password,check_password
from testweb.models import Signup
from testweb.models import Signup1
from testweb.models import Student
from testweb.models import Result
from testweb.models import Reset
from testweb.models import Test
from datetime import date,timedelta
from testweb.models import Math
from testweb.models import MathResult
from testweb.models import Chemistry
from testweb.models import ChemistryResult
from testweb.models import Physics
from testweb.models import PhysicsResult
from testweb.models import TeacherSignup
from testweb.models import Teacher
from rest_framework import viewsets
from testweb.serializers import TestSerializer
import random
import uuid
from .email import send_forget_password_mail
import time


class TestSet(viewsets.ModelViewSet):
    queryset = Test.objects.all()
    serializer_class = TestSerializer
    



#signup function for teachers
def signupteacher(request):
    context = {'success':False}
    if request.method == 'POST':
        name = request.POST['Name']
        email = request.POST['Email']
        password = request.POST['Pass']
        subject = request.POST['subject']
        password = make_password(password)
        
        if(len(Signup.objects.filter(srollno=email)) or len(TeacherSignup.objects.filter(empid=email))):
            print("Inside")
            context = {'success':False}
        else:
            context = {'success':True}
            teachersignup = TeacherSignup(empid=email,ename=name,epass=password,esubject=subject)
            teacher = Teacher(empid=email,ename=name,esubject=subject)
            teachersignup.save()
            teacher.save()
            print(email,subject,name)
        print("Outside") 
    return render(request,'signupteacher.html',context=context)





#signin for teacher
def signinteacher(request):
    context = {'success':False}
    if request.method == "POST":
        email = request.POST["Email"]
        password = request.POST["Pass"]
        candiate_password_from_database = ""
        if(len(TeacherSignup.objects.filter(empid = email))):
            candiate_password_from_database = TeacherSignup.objects.get(empid = email)
        else:
            return render (request,'signupteacher.html')
        
        check = check_password(password,candiate_password_from_database.epass)
        candidate = TeacherSignup.objects.filter(empid=email)
        
        if(len(TeacherSignup.objects.filter(empid = email)) and check==True):
            request.session['TeacherEmail'] = candidate[0].empid
            request.session['Pass'] = candidate[0].epass
            # print("hi")
            teacher_name = TeacherSignup.objects.get(empid=email)
            context = {'empno':request.session['TeacherEmail'],'teacher':teacher_name.ename,'subject':teacher_name.esubject}
            return render(request,'hometeacher.html',context)
        else:
            context = {'message':'Your email or password was wrong','success':True}
            return render(request,'signinteacher.html',context)

    return render(request,'signinteacher.html')







#signin for students
def signin(request):
    passs = Signup.objects.all()
    count=0
    if request.method=='POST':
        email = request.POST['Email']
        passwords = request.POST['Pass']
        candiate_password_from_database=""
        if(len(Signup.objects.filter(srollno=email))):
            candiate_password_from_database = Signup.objects.get(srollno = email)
        else:
            return render(request,'signup.html')
        # print(make_password(passwords))
        password = check_password(passwords,candiate_password_from_database.spass)
        candidate = Signup.objects.filter(srollno=email)
        if(len(Signup.objects.filter(srollno=email)) and password==True):
            request.session['Email'] = candidate[0].srollno
            request.session['Pass'] = candidate[0].spass
            student_name = Signup.objects.get(srollno=email).sname
            context = {'rollno':request.session['Email'],'studentname':student_name}
            return render(request,'home.html',context)
        else:
            count=1
            context = {'student':passs,'yes':"Wrong Password or Email",'count':count}
            return render(request,'signin.html',context)
    else:
        return render(request,'signin.html')





#signup function for students
def signup(request):
    size = Signup.objects.count()
    context = {'success':False}
    if request.method == 'POST':
        name = request.POST['Name']
        rollNo = request.POST['Email']
        password = request.POST['Pass']
        password = make_password(password)
        signup = Signup(sname = name,srollno=rollNo,spass=password)
        signup1 = Signup1(sname = name,srollno=rollNo,spass=password)
        student = Student(srollno = rollNo, sname=name)
       
        print(size)
        if len(Signup.objects.filter(srollno=rollNo)) or len(TeacherSignup.objects.filter(empid=rollNo)):
            context={'success':False}
        else:
            print(name,rollNo,password)
            signup.save()
            signup1.save()
            student.save()
            context={'success':True}
    return render(request,'signup.html',context)

  
  
  
  
  
#forget password  for teacher
def forget(request):
    if request.method =='POST':
        email = request.POST['Email']
        print(email)
        # emails = request.POST['TeacherEmail']
        if(len(Signup1.objects.filter(srollno=email))):
            token = str(uuid.uuid4())
            context = {'message':"Link has been sent.",'count':1}
            reset_student_password = Reset(srollno = email,stoken=token)
            send_forget_password_mail(email,token)
            reset_student_password.save()
            return render(request,'forget.html',context)
        
        elif(len(TeacherSignup.objects.filter(empid=email))):
            token = str(uuid.uuid4())
            context = {'message':"Link has been sent.",'count':1}
            reset_teacher_password = Reset(srollno = email,stoken=token)
            send_forget_password_mail(email,token)
            reset_teacher_password.save()
            print(email)
            return render(request,'forget.html',context)
        
        else:
            return render(request,'signup.html')
    return render(request,'forget.html')
  



  

#confirm password reset  student
def confirm(request):
    object = Reset.objects.get(sid=Reset.objects.latest('sid').sid)
    
    if object.date == date.today():
        if request.method == 'POST':
            password = request.POST['Pass1']
            password1 = request.POST['Pass']
            
            if (len(Signup.objects.filter(srollno = object.srollno))) and password == password1:
                student_password_change = Signup.objects.get(srollno = object.srollno)
                student_password_change1 = Signup1.objects.get(srollno = object.srollno)
                student_password_change.spass = make_password(password)
                student_password_change1.spass = make_password(password)
                object.spass = make_password(password)
                print('changed',object.srollno)
                student_password_change.save()
                object.save()
                student_password_change1.save()
                return render(request,'confirm.html')
            
            elif (len(TeacherSignup.objects.filter(empid = object.srollno))):
                teacher_password_change = TeacherSignup.objects.get(empid = object.srollno)
                teacher_password_change.epass = make_password(password)
                object.spass = make_password(password)
                print('changed',object.srollno)
                teacher_password_change.save()
                object.save()
                return render(request,'confirm.html')
            else:
                return render(request,'notconfirm.html')
    else:
        return render(request,'linkexpired.html')







#link expired page
def linkexpired(request):
    return render(request,'linkexpired.html')








#if password not changed properly 
def notconfirm(request):
    return render(request,'notconfirm.html')
  
  
  
 
 
  
#changepassword
def changepassword(request,token):
    return render(request,'changepassword.html')
 
    
    
    
    
    
#home page 
def home(request):
    if 'Email' not in request.session.keys():
        return render(request,'signin.html')
    else:
        print(request.session.get('Email'))
        student_name = Student.objects.get(srollno=request.session['Email'])
        context = {'rollno':request.session['Email'],'studentname':student_name.sname}
        return render(request,'home.html',context)





#home page 
def hometeacher(request):
    if 'TeacherEmail' not in request.session.keys():
        return render(request,'signinteacher.html')
    else:
        print(request.session.get('TeacherEmail'))
        teacher_name = TeacherSignup.objects.get(empid=request.session['TeacherEmail'])
        context = {'empno':request.session['TeacherEmail'],'teacher':teacher_name.ename,'subject':teacher_name.esubject}
        return render(request,'hometeacher.html',context)





#paperset for student
def paperset(request):
    if 'TeacherEmail' not in request.session.keys():
        return render(request,'signinteacher.html')
    else:
        teacher_name = TeacherSignup.objects.get(empid=request.session['TeacherEmail'])
        total_number_of_question=0
        if teacher_name.esubject.lower() == "physics":

testweb/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
  {% comment %} <link rel="icon" href="{% static '1.png' %}"> {% endcomment %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <style>
    body {
      background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
      background-size: 10000vh;
      animation: gradient 15s ease infinite;
    }
    #quiz-name{
      background-color: rgb(253, 143, 143);
      margin-top: 20px;
      text-align: center;
      border: 2px solid black;
      border-radius: 6px;
  }
  
  .ques{
      border:2px solid black;
      border-radius: 10px;
      background-color: rgb(243, 231, 214);
      padding: 15px;
  }
  
  
  .box{
      padding: 15px;
      margin: auto;
      width:65%;
      height: 15%;
      box-shadow: inset;
      background-color: rgb(255, 255, 255);
      color: rgb(1, 67, 67);
      box-shadow: 6px 4px 4px rgba(0,0,0,0.3);
      border-radius: 10px;
      display: flex;
      justify-content: center;
      align-items: center;
      overflow:hidden;
      animation: mymove 5s infinite;
  }
  
  
  
  @keyframes mymove {
    0%   {top: 0px; background: rgb(255, 255, 255); width: 45%;}
    100% {top: 0px; background: rgb(255, 255, 183); width: 60%;}
  }


  @keyframes mymoves {
    0%   {top: 0px; background: rgb(255, 255, 255); width: 60%;}
    100% {top: 0px; background: rgb(255, 255, 183); width: 70%;}
  }
  
  .Test{
      display: flex;
      justify-content: center;
      align-items: center;
  }
  
  
  .boxs{
      width: 100%;
      color: rgb(27, 27, 27);
      border-radius: 10px;
      display: flex;
      justify-content: space-between;
  }
  
  
  
  .but{
      width:75px;
      height:30px;
      border: 2px solid rgb(95, 95, 95);
      display: flex;
      padding: 3px;
      justify-content: space-around;
      border-radius: 10px;
      text-decoration: none;
      cursor: pointer;
      color: black;
  }
  
  
  .buts{
      width:15px;
      height:30px;
      display: flex;
      padding: 3px;
      justify-content: space-around;
      border-radius: 10px;
      text-decoration: none;
  }
  
  
  .start{
      margin-top:10px ;
      color: rgb(1, 67, 67);
      border-radius: 10px;
      display: flex;
      justify-content:space-between;
  }
  
  
  
  .new{
      width: 50px;
      height: fit-content;
      display: flex;
      border-radius: 5px;
      justify-content: center;
      background-color: rgb(0, 255, 255);
  }
    @keyframes gradient {
      0% {
        background-position: 0% 50%;
      }
      50% {
        background-position: 100% 50%;
      }
      100% {
        background-position: 0% 50%;
      }
    }
    .a{
      text-decoration:none;
      color:black;
      margin:20px;
    }

.wrapper {
  display: flex;
  width: 100%;
  height:100%;
  justify-content: center;
  align-items: center;
}

.wrapper1 {
  margin: 20px;
  display: flex;
  padding: 15px;
  width:100%;
  height: 40%;
  box-shadow: inset;
  background-color: rgb(255, 255, 255);
  color: rgb(1, 67, 67);
  box-shadow: 6px 4px 4px rgba(0,0,0,0.3);
  border-radius: 10px;
  flex-direction: column;
  justify-content: space-between;
  animation: mymove 10s infinite;
}

@media screen and (max-width: 500px) {
  .wrapper {
    display: block;
    width: 100%;
    height: 100%;
    margin: 20px auto;
  }

  .wrapper1 {
    padding: 15px;
    margin: auto;
    width:60%;
    height: 20%;
    box-shadow: inset;
    background-color: rgb(255, 255, 255);
    color: rgb(1, 67, 67);
    box-shadow: 6px 4px 4px rgba(0,0,0,0.3);
    border-radius: 10px;
    flex-direction: column;
    justify-content: space-between;
    animation: mymoves 20s infinite;
  }
}

.p{
  color:white;
  left: 10px;
  font-size:20px;
  display: flex;
  position: absolute;
  justify-content: center;
  align-items: center;
  width: 50px;
  height: 50px;
  text-decoration:none;
  box-shadow: var(--boxShadow);
  border-radius: 50px;
}
    
  </style>
  <title>DashBoard</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'testweb:Home'%}">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  About You
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">{{rollno}}</a></li>
                  
                </ul>
              </li>
            </ul>
            <form class="d-flex" role="search">
              
              <a href="{% url 'testweb:logout'%}" class="dropdown-item mx-2" >LogOut</a>
            </form>
          </div>
        </div>
      </nav>
      <a href="{% url 'testweb:Home' %}" class='p'>Back</a>

      <div class='Test' style='margin-top:10px; margin-bottom:15px;'>
        <h2>Online Test Website</h2>
      </div>

      <div class='box' style='margin-bottom:25px;'>
        <h2>Hi {{studentname}}, Welcome</h2>
      </div>

<div class="wrapper">
    <div class='wrapper1'>
      <div class='boxs'>
        <h6>Questions</h6>
        <h6 class='new'>New</h6>
      </div>
      <div class='start'>
        <h3>Physics </h3>
        <a class='but' style='margin-top:20px;' href='{% url 'testweb:physics' %}'><i class="fa-solid fa-play buts" ></i> Start</a>
      </div>
      <p>Test Do</p>
    </div>



    <div class='wrapper1' style='margin-top:25px;'>
      <div class='boxs'>
        <h6>Questions</h6>
        <h6 class='new'>New</h6>
      </div>
      <div class='start'>
        <h3>Chemistry</h3>
        <a class='but' style='margin-top:20px;' href='{% url 'testweb:chemistry' %}'><i class="fa-solid fa-play buts" ></i> Start</a>
      </div>
      <p>Mistake Allowed</p>
    </div>
  </div>


 <div class="wrapper"> 

    <div class='wrapper1' style='margin-top:25px;'>
      <div class='boxs'>
        <h6>Questions</h6>
        <h6 class='new'>New</h6>
      </div>
      <div class='start'>
        <h3>Math</h3>
        <a class='but' style='margin-top:20px;' href='{% url 'testweb:math' %}'><i class="fa-solid fa-play buts" ></i> Start</a>
      </div>
      <p>Mistake Allowed</p>
    </div>



    <div class='wrapper1' style='margin-top:25px;'>
      <div class='boxs'>
        <h6>Questions</h6>
        <h6 class='new'>New</h6>
      </div>
      <div class='start'>
        <h3>General Knowledge</h3>
        <a class='but' style='margin-top:20px;' href='{% url 'testweb:gs' %}'><i class="fa-solid fa-play buts" ></i> Start</a>
      </div>
      <p>Mistake Allowed</p>
    </div>
  </div>


    <br><br><br>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/13fdc47a54.js" crossorigin="anonymous"></script>
</body>

testweb/templates/hometeacher.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  {% comment %} <link rel="icon" href="{% static '1.png' %}"> {% endcomment %}
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>


  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <style>
    body {
      background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
      background-size: 10000vh;
      animation: gradient 15s ease infinite;
    }
    
    @keyframes gradient {
      0% {
        background-position: 0% 50%;
      }
      50% {
        background-position: 100% 50%;
      }
      100% {
        background-position: 0% 50%;
      }
    }
    .a{
      text-decoration:none;
      color:black;
      margin:20px;
    }
    #quiz-name{
      background-color: rgb(253, 143, 143);
      margin-top: 20px;
      text-align: center;
      border: 2px solid black;
      border-radius: 5px;
  }
  
  .ques{
      border:2px solid black;
      border-radius: 10px;
      background-color: rgb(243, 231, 214);
      padding: 15px;
  }
  
  
  .box{
      padding: 15px;
      margin: auto;
      width:65%;
      height: 15%;
      box-shadow: inset;
      background-color: rgb(255, 255, 255);
      color: rgb(1, 67, 67);
      box-shadow: 6px 4px 4px rgba(0,0,0,0.3);
      border-radius: 10px;
      display: flex;
      justify-content: center;
      align-items: center;
      overflow:hidden;
      animation: mymove 5s infinite;
  }
  
  
  
  @keyframes mymove {
    0%   {top: 0px; background: rgb(255, 255, 255); width: 60%;}
    100% {top: 0px; background: rgb(255, 255, 183); width: 65%;}
  }
  
  .Test{
      display: flex;
      justify-content: center;
      align-items: center;
  }
  
  
  .boxs{
      width: 100%;
      color: rgb(27, 27, 27);
      border-radius: 10px;
      display: flex;
      justify-content: space-between;
  }
  
  
  
  .but{
      width:75px;
      height:30px;
      border: 2px solid rgb(95, 95, 95);
      display: flex;
      padding: 3px;
      justify-content: space-around;
      border-radius: 10px;
      text-decoration: none;
      cursor: pointer;
      color: black;
  }
  
  
  .buts{
      width:15px;
      height:30px;
      display: flex;
      padding: 3px;
      justify-content: space-around;
      border-radius: 10px;
      text-decoration: none;
  }
  
  
  .start{
      margin-top:10px ;
      color: rgb(1, 67, 67);
      border-radius: 10px;
      display: flex;
      justify-content:space-between;
  }
  
  
  .new{
      width: 50px;
      height: fit-content;
      display: flex;
      border-radius: 5px;
      justify-content: center;
      background-color: rgb(0, 255, 255);
  }
  
.wrapper
{
  margin-top:55px;
  display: flex;
  width: 100%;
  height:150px;
  justify-content: space-between;
  align-items: center;
}

.wrapper1 
{
  margin: 20px;
  display: flex;
  padding: 30px;
  width:30%;
  height: 100%;
  box-shadow: inset;
  background-color: rgb(255, 255, 255);
  color: rgb(1, 67, 67);
  box-shadow: 6px 4px 4px rgba(0,0,0,0.3);
  border-radius: 10px;
  flex-direction: column;
  justify-content: space-between;
  animation: mymove 10s infinite;
}


@media screen and (max-width: 800px) {
  .wrapper {
    display: block;
    width: 100%;
    height: 100%;
    margin: 20px auto;
  }

  .wrapper1 
  {
    padding: 15px;
    margin: auto;
    width:60%;
    height: 20%;
    box-shadow: inset;
    background-color: rgb(255, 255, 255);
    color: rgb(1, 67, 67);
    box-shadow: 6px 4px 4px rgba(0,0,0,0.3);
    border-radius: 10px;
    flex-direction: column;
    justify-content: space-between;
    animation: mymoves 20s infinite;
  }
}
.p{
  color: white;
  left: 10px;
  font-size:20px;
  display: flex;
  position: absolute;
  justify-content: center;
  align-items: center;
  width: 50px;
  height: 50px;
  text-decoration:none;
  box-shadow: var(--boxShadow);
  border-radius: 50px;
}
  </style>
  <title>Teacher</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'testweb:Hometeacher'%}">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  About You
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">{{empno}}</a></li>
                  
                </ul>
              </li>
            </ul>
            <form class="d-flex" role="search">
              
              <a href="{% url 'testweb:logoutteacher'%}" class="dropdown-item mx-2" >LogOut</a>
            </form>
          </div>
        </div>
      </nav>
      <a href="{% url 'testweb:Hometeacher' %}" class='p'>Back</a>
      <div class='Test' style='margin-top:10px; margin-bottom:15px;'>
        <h2>Online Test Website</h2>
      </div>

      <div class='box' style='margin-bottom:25px;'>
        <h2>Hello {{teacher}} sir/mam, Welcome</h2>
      </div>

  <div class="wrapper">
    <div class='wrapper1'>
      <div class='boxs'>
        <h6>Add Questions</h6>
        <h6 class='new'>New</h6>
      </div>
      <div class='start'>
        <h3>{{subject}} </h3>
        <a class='but' style='margin-top:20px;' href='{% url 'testweb:paperset' %}'><i class="fa-solid fa-plus"></i>Add</a>
      </div>
    </div>



    <div class='wrapper1' style='margin-top:25px;'>
      <div class='boxs'>
        <h6>See All Questions of</h6>
        <h6 class='new'>New</h6>
      </div>
      <div class='start'>
        <h3>{{subject}}</h3>
        <a class='but' style='margin-top:20px;' href='{% url 'testweb:totalquestion' %}'><i class="fa-solid fa-question"></i>Ques</a>
      </div>
    </div>
   
    <div class='wrapper1' style='margin-top:25px;'>
      <div class='boxs'>
        <h6>See Marks of the </h6>
        <h6 class='new'>New</h6>
      </div>
      <div class='start'>
        <h3>Students</h3>
        <a class='but' style='margin-top:20px;' href='{% url 'testweb:marks' %}'><i class="fa-solid fa-marker"></i>Marks</a>
      </div>
    </div>
  </div>
<br><br>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/13fdc47a54.js" crossorigin="anonymous"></script>
</body>